### PR TITLE
add dynamic button component

### PR DESCRIPTION
**Pull request by DeanIsHere**
I've created reusable component for dynamic button, it requires title and onClick parameters. title parameter will insert button title (text inside button) and onChange will insert any logic (ofc it has to in function form) you want to execute when the button pressed.

Component name and how it's used on EditProfileBox

`<LoadingButton onClick={() => handleUpdate()} title="UPDATE"/>`

notes: I don't check every possibly button design we may have, i will add more parameters if it needed like variant or something else

### CODE REVIEW

**Comment by RifqiAdhityatama** [comment]
LGTM

**Comment by argikurnia1** [comment]
LGTM (2)

**Comment by argikurnia1** [comment]
tapi masi ada bug

**Comment by DeanIsHere** [comment]
oke bug nya gw benerin dulu

**Comment by RifqiAdhityatama** [comment]
ehiya mas dean, ada bug sedikit. tolong di cek

**Comment by DeanIsHere** [comment]
tapi merge dulu aja ya

**Pull request merged**
