### PR TITLE
change register user algorithms and apply redux on edit profile

### PR DESCRIPTION
**Pull request by DeanIsHere**
I've done two major things, 

first applying Argis's redux on my edit profile page and do a bit experiment on calling dispatch inside update function in order to update redux store according to updated database event, it works but affected to profile page. before I do some data change on edit profile page, all data can be shown on profile page but after data updating and click back on profile page, all data that shown before becomes null, though the data on current collection was updated as expected, also if I reload the page all data on redux store will be lost and cause error (idk if there are solution for this or not)

second is change push method to set (included change on db refs) on register user function on action.js,  in order to synchronize auth UID and game_user UID and works as fine as expected, I reserved id_player until everyone done with their code refactoring and will be deleted, others fuction refactoring on action.js will be done ASAP

### CODE REVIEW

**Comment by RifqiAdhityatama** [comment]
lanjutkan

**Comment by argikurnia1** [comment]
gaskeunnnn

**Comment by DeanIsHere** [comment]
tolong gaes di ripiuw lagi, kalo ada yang mau ditanyakan monggo

**Comment by RifqiAdhityatama** [comment]
Lanjutkan mas dean

**Comment by DeanIsHere** [comment]
gw merge ya, nanti cek error masing masing ye wkwk

**Pull request merged**
